---
- name: Setup Kubernetes (kubectl + minikube) and deploy weather app
  hosts: localhost
  become: yes
  vars:
    kubectl_download_url: "https://dl.k8s.io/release"
    minikube_download_url: "https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64"

  tasks:
    - name: Update and upgrade APT packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Get latest Kubernetes version
      shell: "curl -L -s https://dl.k8s.io/release/stable.txt"
      register: k8s_version

    - name: Download kubectl binary
      get_url:
        url: "{{ kubectl_download_url }}/{{ k8s_version.stdout }}/bin/linux/amd64/kubectl"
        dest: /tmp/kubectl
        mode: '0755'

    - name: Download kubectl checksum
      get_url:
        url: "{{ kubectl_download_url }}/{{ k8s_version.stdout }}/bin/linux/amd64/kubectl.sha256"
        dest: /tmp/kubectl.sha256

    - name: Verify kubectl checksum
      shell: "echo $(cat /tmp/kubectl.sha256) /tmp/kubectl | sha256sum --check"
      register: checksum_result
      failed_when: "'OK' not in checksum_result.stdout"

    - name: Install kubectl
      copy:
        src: /tmp/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'


    - name: Download minikube binary
      get_url:
        url: "{{ minikube_download_url }}"
        dest: /tmp/minikube
        mode: '0755'

    - name: Install minikube
      copy:
        src: /tmp/minikube
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Start Minikube
      shell: "minikube start"
      become: false
      environment:
        CHANGE_MINIKUBE_NONE_USER: "true"

    - name: Copy k8s/deployment.yaml to server
      copy:
        src: k8s/deployment.yaml
        dest: /tmp/deployment.yaml

    - name: Copy k8s/service.yaml to server
      copy:
        src: k8s/service.yaml
        dest: /tmp/service.yaml

    - name: Pause for 5 seconds
      ansible.builtin.pause:
        seconds: 5

    - name: Apply weather app Deployment
      shell: "kubectl apply -f /tmp/deployment.yaml"
      become: false
      environment:
        CHANGE_MINIKUBE_NONE_USER: "true"

    - name: Apply weather app Service
      shell: "kubectl apply -f /tmp/service.yaml"
      become: false
      environment:
        CHANGE_MINIKUBE_NONE_USER: "true"

